### ISSUE TITLE
请问出现了这个问题_pickle.UnpicklingError: invalid load key, '\xad'.，应该如何解决呀？有点紧急，非常感谢！

### ISSUE THREAD

**Issue by strawyer** [VISION-SJTU/3dSwap#8]
(3dSwap) root@autodl-container-7dda1180fa-17262490:~/3dSwap# python run_3dSwap.py
Setting up [LPIPS] perceptual loss: trunk [alex], v[0.1], spatial [off]
Loading model from: /root/miniconda3/envs/3dSwap/lib/python3.8/site-packages/lpips/weights/v0.1/alex.pth
Traceback (most recent call last):
  File "run_3dSwap.py", line 23, in <module>
    run_3dSwap(args)
  File "run_3dSwap.py", line 10, in run_3dSwap
    coach = FaceSwapCoach()
  File "/root/3dSwap/models/faceswap_coach.py", line 95, in __init__
    self.encoder = self.load_encoder()
  File "/root/3dSwap/models/faceswap_coach.py", line 102, in load_encoder
    encoder_ckpt = torch.load('checkpoints/encoder.pt')
  File "/root/miniconda3/envs/3dSwap/lib/python3.8/site-packages/torch/serialization.py", line 593, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/root/miniconda3/envs/3dSwap/lib/python3.8/site-packages/torch/serialization.py", line 762, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, '\xad'.

**Comment by lyx0208** [comment]
Really sorry to see this issue so late…… But actually I didn't meet this problem on my own machine. Can you provide more information?
